version: '3'

services:
  ordersDB:
    image: postgres:14.5
    restart: always
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    container_name: ordersDB
    volumes:
      - ./postgres:/var/lib/postgresql/data